### ISSUE TITLE
Camera Calibration

### ISSUE THREAD

**Issue by rickstaa** [rickstaa/panda_autograsp#29]
To work with the physical robot, I need to do a camera calibration to obtain the extrinsic transformation matrix. 

# Todos 

## Required
- [x] Get chessboard image and print on a A3.
    - [x] Add chessboard to package.
- [x] Try out ros Calibration function.
- [x] Retreive color intrinsic variables.
- [x] Create calibration script to get *T_camera_world*.
- [ ] Create calibration script to get *T_wold_robot*.

## Optional
- [ ] Retreive IR calibration values 

## Chessboard image
The chessboard for the calibration was created using [http://rgbdemo.org](http://rgbdemo.org/index.php/Documentation/Calibration) and can be found in the `/data/calib` folder.

# Factory or own calibration
As suggested by [The libfreenect2 toolbox](https://openkinect.github.io/libfreenect2/classlibfreenect2_1_1Freenect2Device.html#a3343e3656ef4ea26650f7e2884aa129c). It is advised to use the factory values for the colour intrinsic variables and obtain the depth intrinsic parameters through calibration.

## How to get these parameters
These parameters can be retrieved using the [pylibfreenect2 toolbox](device.getColorCameraParams()). However, in v0.1.2 the distortion parameters are not available through the `getIrParams()` method. In v0.1.3 they are available.

# Toolbox
- [windows toolbox](http://graphics.cs.msu.ru/en/node/909)

# Other useful sources
- [opencv calibration python3 tutorial](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_calib3d/py_calibration/py_calibration.html)
- [Explained how to get calibration variables](https://stackoverflow.com/questions/44537400/how-to-kinect-rgb-depth-camera-calibration-by-gml-c-camera-calibration-toolb#44538234)
- [ROS calibration tool](https://github.com/code-iai/iai_kinect2)
- [python3 calib tool](https://github.com/danilogr/KinectV2Calibration)
- [Depth camera calibration](http://doc-ok.org/?p=289)
