### ISSUE TITLE
Setup system on the franka system

### ISSUE THREAD

**Issue by rickstaa** [rickstaa/panda_autograsp#51]
# Todos
- [x] Create a user account
- [x] :warning: Add container ([see container problem](#Container-problem))
- [x] Test If I'm able to control the robot
- [x] Perform safety checks with Kees

## Setup on franka01
I need to set up my user account and add the docker container to the franka01 computer.

### Problem
While trying to get the code to run on the `franka01` robot I run into the problem that the Nvidia drivers do not work with the [Franka realtime kernel](https://frankaemika.github.io/docs/installation_linux.html#setting-up-the-real-time-kernel) ([See this topic](https://devtalk.nvidia.com/default/topic/777636/simply-impossible-to-use-an-nvidia-card-on-a-real-time-kernel-no-musician-can-use-nvidia-/)).   There are some solutions but they or require a modification of the NVIDIA headers or the use of a patched real-time kernel. As we need to use the REALTIME kernel supplied by Franka this is not going to work.

### Container problem
Currently, singularity does not yet support AMD GPU computing. This feature will be rolled out before the end of the year ([see this blog post](https://sylabs.io/2019/06/towards-generalized-gpu-support-in-the-singularity-container-runtime-an-isc-preview-involving-amd-radeon-instinct-accelerators-and-the-rocm-open-software-platform/)). I can, therefore, do 3 things:
- Convert singularity recipe to docker recipe
-  Convert singularity recipe to a bash installation script (Easiest preferred)
